# Generated by Django 5.0.3 on 2024-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornapal_app', '0003_recipe_ingredients_recipeingredient_is_optional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='recipe_images'),
        ),
    ]
