# Generated by Django 5.0.3 on 2024-03-31 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornapal_app', '0004_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jornapal_app.recipe'),
        ),
    ]
