# Generated by Django 5.0.3 on 2024-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornapal_app', '0005_remove_recipe_images_image_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='is_optional',
        ),
    ]
